### ISSUE TITLE
Optional chaining in typescript

### ISSUE THREAD

**Issue by JasCodes** [g-plane/pluggable-babel-eslint#1]
Hey @g-plane 
Optional chaining works in javascript but not in typescript
 
.babelrc
```
{
    "presets": [
        "@babel/typescript"
    ],
    "plugins": [
        "@babel/plugin-proposal-optional-chaining"
    ]
}
```
.eslintrc.json
```
{
    "parser": "pluggable-babel-eslint"
}
```

**Comment by g-plane** [comment]
Yes, TypeScript doesn't support optional chaining now. What's your problem?

**Comment by JasCodes** [comment]
so babel plugins can't effect typescript?

**Comment by g-plane** [comment]
Have you encountered any errors?

**Comment by g-plane** [comment]
> 
> 
> so babel plugins can't effect typescript?

The optional chaining is a proposal of ES spec, not related to TypeScript. So if you use this feature in your project, Babel and `pluggable-babel-eslint` can parse it, but TypeScript cannot.

**Comment by JasCodes** [comment]
In most common babel typescript setup tutorials, I come across this setting.

```
{ 	
  "presets": [ 			
    "@babel/typescript" 	
  ], 	
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ] 
}
```
So adding these plugins don't make sense if I only use typescript? and plugins only affect javascript? 
Or is it the case optional chaning plugin only works with javascript?

**Comment by g-plane** [comment]
The `@babel/typescript` preset just strips the type annotations in your source code and it doesn't do any other work.

**Comment by JasCodes** [comment]
If that is the case, optional chaining should work as after striping types its just javascript

**Comment by JasCodes** [comment]
I tried to use optional chaining plugin with typescript with babel-node, for js it works and for ts it doesn't

**Comment by JasCodes** [comment]
does plugins apply before or after type striping with typescript preset?

**Comment by g-plane** [comment]
I think you are misunderstanding something.

- This package is for ESLint, not for transpiling or running your code.
- Optional chaining is NOT supported in TypeScript. So, if you use that feature and run `tsc` command, you will get errors. However, the Babel can parse it.

**Comment by JasCodes** [comment]
Gotcha, but still curious that babel-node should work then, only when we do tsc which will be doing type checking it should fail. But that seems to be not the case.

**Comment by g-plane** [comment]
You can open an issue at Babel's repo.

**Comment by g-plane** [comment]
I'm closing this now. If you have other questions, feel free to open another issue.
